version: '3.4'
services:

  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    networks:
      - network-app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    image: openjdk:11
    container_name: app
    restart: always
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:                                                                               
        APP_VERSION: '0.0.1-SNAPSHOT'
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    networks:
      - network-app
    ports:
      - '9191:9191'
      - '8888:8888'
    expose:
      - '9191'
    depends_on:
      - db

  db:
    image: mariadb:10.2
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootmysql
      - MYSQL_DATABASE=system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    networks:
      - network-app
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql
networks:
  network-app:
volumes:
  db-volume: